services:
  - type: web
    name: gimnasio_app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: master
    repo: https://github.com/estebaan666/gimnasio_app
