services:
  - type: web
    name: gimnasio-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gimnasio_app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
